services:
  nolongerevil:
    container_name: nolongerevil
    image: nolongerevil
    build: .
    restart: unless-stopped
    ports:
      - 7001:80
      - 443:443
    environment:
      - API_ORIGIN=http://192.168.1.1
      - PROXY_PORT=80
      - SQLITE3_ENABLED=true
      - SQLITE3_DB_PATH=./data/test.sqlite
      - ENTRY_KEY_TTL_SECONDS=3600
      - DEBUG_LOGGING=false
      - CERT_DIR=
    volumes:
      - nolongerevil-data:/app/data

volumes:
  nolongerevil-data: