services:
  nolongerevil:
    container_name: nolongerevil
    image: nolongerevil
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8081
    volumes:
      - ./.env.local:/app/.env.local
      - ./data:/app/data